/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)")
public class OpuSInfo implements org.apache.thrift.TBase<OpuSInfo, OpuSInfo._Fields>, java.io.Serializable, Cloneable, Comparable<OpuSInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("OpuSInfo");

  private static final org.apache.thrift.protocol.TField CACHED_FRACTION_FIELD_DESC = new org.apache.thrift.protocol.TField("cachedFraction", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ACCESS_FACTOR_FIELD_DESC = new org.apache.thrift.protocol.TField("accessFactor", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new OpuSInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new OpuSInfoTupleSchemeFactory();

  private java.lang.String cachedFraction; // required
  private java.lang.String accessFactor; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CACHED_FRACTION((short)1, "cachedFraction"),
    ACCESS_FACTOR((short)2, "accessFactor");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CACHED_FRACTION
          return CACHED_FRACTION;
        case 2: // ACCESS_FACTOR
          return ACCESS_FACTOR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CACHED_FRACTION, new org.apache.thrift.meta_data.FieldMetaData("cachedFraction", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ACCESS_FACTOR, new org.apache.thrift.meta_data.FieldMetaData("accessFactor", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(OpuSInfo.class, metaDataMap);
  }

  public OpuSInfo() {
  }

  public OpuSInfo(
    java.lang.String cachedFraction,
    java.lang.String accessFactor)
  {
    this();
    this.cachedFraction = cachedFraction;
    this.accessFactor = accessFactor;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public OpuSInfo(OpuSInfo other) {
    if (other.isSetCachedFraction()) {
      this.cachedFraction = other.cachedFraction;
    }
    if (other.isSetAccessFactor()) {
      this.accessFactor = other.accessFactor;
    }
  }

  public OpuSInfo deepCopy() {
    return new OpuSInfo(this);
  }

  @Override
  public void clear() {
    this.cachedFraction = null;
    this.accessFactor = null;
  }

  public java.lang.String getCachedFraction() {
    return this.cachedFraction;
  }

  public OpuSInfo setCachedFraction(java.lang.String cachedFraction) {
    this.cachedFraction = cachedFraction;
    return this;
  }

  public void unsetCachedFraction() {
    this.cachedFraction = null;
  }

  /** Returns true if field cachedFraction is set (has been assigned a value) and false otherwise */
  public boolean isSetCachedFraction() {
    return this.cachedFraction != null;
  }

  public void setCachedFractionIsSet(boolean value) {
    if (!value) {
      this.cachedFraction = null;
    }
  }

  public java.lang.String getAccessFactor() {
    return this.accessFactor;
  }

  public OpuSInfo setAccessFactor(java.lang.String accessFactor) {
    this.accessFactor = accessFactor;
    return this;
  }

  public void unsetAccessFactor() {
    this.accessFactor = null;
  }

  /** Returns true if field accessFactor is set (has been assigned a value) and false otherwise */
  public boolean isSetAccessFactor() {
    return this.accessFactor != null;
  }

  public void setAccessFactorIsSet(boolean value) {
    if (!value) {
      this.accessFactor = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case CACHED_FRACTION:
      if (value == null) {
        unsetCachedFraction();
      } else {
        setCachedFraction((java.lang.String)value);
      }
      break;

    case ACCESS_FACTOR:
      if (value == null) {
        unsetAccessFactor();
      } else {
        setAccessFactor((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CACHED_FRACTION:
      return getCachedFraction();

    case ACCESS_FACTOR:
      return getAccessFactor();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CACHED_FRACTION:
      return isSetCachedFraction();
    case ACCESS_FACTOR:
      return isSetAccessFactor();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof OpuSInfo)
      return this.equals((OpuSInfo)that);
    return false;
  }

  public boolean equals(OpuSInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_cachedFraction = true && this.isSetCachedFraction();
    boolean that_present_cachedFraction = true && that.isSetCachedFraction();
    if (this_present_cachedFraction || that_present_cachedFraction) {
      if (!(this_present_cachedFraction && that_present_cachedFraction))
        return false;
      if (!this.cachedFraction.equals(that.cachedFraction))
        return false;
    }

    boolean this_present_accessFactor = true && this.isSetAccessFactor();
    boolean that_present_accessFactor = true && that.isSetAccessFactor();
    if (this_present_accessFactor || that_present_accessFactor) {
      if (!(this_present_accessFactor && that_present_accessFactor))
        return false;
      if (!this.accessFactor.equals(that.accessFactor))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCachedFraction()) ? 131071 : 524287);
    if (isSetCachedFraction())
      hashCode = hashCode * 8191 + cachedFraction.hashCode();

    hashCode = hashCode * 8191 + ((isSetAccessFactor()) ? 131071 : 524287);
    if (isSetAccessFactor())
      hashCode = hashCode * 8191 + accessFactor.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(OpuSInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCachedFraction()).compareTo(other.isSetCachedFraction());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCachedFraction()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cachedFraction, other.cachedFraction);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAccessFactor()).compareTo(other.isSetAccessFactor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccessFactor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accessFactor, other.accessFactor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("OpuSInfo(");
    boolean first = true;

    sb.append("cachedFraction:");
    if (this.cachedFraction == null) {
      sb.append("null");
    } else {
      sb.append(this.cachedFraction);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("accessFactor:");
    if (this.accessFactor == null) {
      sb.append("null");
    } else {
      sb.append(this.accessFactor);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OpuSInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public OpuSInfoStandardScheme getScheme() {
      return new OpuSInfoStandardScheme();
    }
  }

  private static class OpuSInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<OpuSInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, OpuSInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CACHED_FRACTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cachedFraction = iprot.readString();
              struct.setCachedFractionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ACCESS_FACTOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.accessFactor = iprot.readString();
              struct.setAccessFactorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, OpuSInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.cachedFraction != null) {
        oprot.writeFieldBegin(CACHED_FRACTION_FIELD_DESC);
        oprot.writeString(struct.cachedFraction);
        oprot.writeFieldEnd();
      }
      if (struct.accessFactor != null) {
        oprot.writeFieldBegin(ACCESS_FACTOR_FIELD_DESC);
        oprot.writeString(struct.accessFactor);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OpuSInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public OpuSInfoTupleScheme getScheme() {
      return new OpuSInfoTupleScheme();
    }
  }

  private static class OpuSInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<OpuSInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, OpuSInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCachedFraction()) {
        optionals.set(0);
      }
      if (struct.isSetAccessFactor()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetCachedFraction()) {
        oprot.writeString(struct.cachedFraction);
      }
      if (struct.isSetAccessFactor()) {
        oprot.writeString(struct.accessFactor);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, OpuSInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.cachedFraction = iprot.readString();
        struct.setCachedFractionIsSet(true);
      }
      if (incoming.get(1)) {
        struct.accessFactor = iprot.readString();
        struct.setAccessFactorIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

